Add script to deploy to kovan
BellwoodStudios/optimism-dai-bridge pull request #21
Opened 2021-05-11 13:03 UTC by krzkaczor

2021-05-11 16:45 UTC, hexonaut approved these changes
LGTM 👍 Perhaps the deployed contracts could have the code verified on Etherscan?

2021-05-13 13:44 UTC, hexonaut requested changes
Thinking more on this I don't like the private key in the code. Should be done in an environment variable or json wallet file I think (or maybe .env file specifying this?).

Rest of it looks good after that.

2021-05-13 13:44 UTC, hexonaut commented on scripts/deployMainnet.ts
>  const L2_DEPLOYER_PRIV_KEY = '6ea93392eb84fad521111def2e8fbd9c45c2b085907797e1a60a210d5bf7089d'
I think we should avoid putting private keys in the code. It's a bad practise as even if there is no funds on there currently, someone may forget in the future that this is public. Perhaps some gitignore'd json wallet file is a better way to go about this? Alternatively an environment variable could work.

2021-05-14 09:30 UTC, krzkaczor commented
@hexonaut Yeah, I guess you are right. I wanted to make it dead simple to use at first.

2021-05-14 11:18 UTC, hexonaut approved these changes
LGTM 👍

2021-05-14 11:42 UTC, merged